# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Restore gradle.properties
      run: |
        echo "github_maven_user=arhacc" >> gradle.properties
        echo "github_maven_password=${{ secrets.GITHUB_TOKEN }}" >> gradle.properties
    - name: Extract tag
      id: extract_tag
      run: |
        TAG=$(git describe --tags)
        echo "TAG=${TAG}" >> $GITHUB_OUTPUT
    - name: Publish to GitHub Packages
      run: |
        TAG=$(cat $GITHUB_OUTPUT | grep TAG | awk -F= '{print $2}')
        ./gradlew publish -ParchiveName=xpu-sdk-libs-v${{ TAG }}.jar

